# SPRING -------------------------------------------------------------------------------------------
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: calendar-api
          uri: http://calendar-api
          predicates:
            - Path=/api/calendar/**
        - id: calendar-api-doc
          uri: http://calendar-api
          predicates:
            - Path=/calendar/**
          filters:
            - RewritePath=/calendar/(?<path>.*), /$\{path}

        - id: calendar-report-api
          uri: http://calendar-report-api
          predicates:
            - Path=/api/calendar-report/**
        - id: calendar-report-api-doc
          uri: http://calendar-report-api
          predicates:
            - Path=/calendar-report/**
          filters:
            - RewritePath=/calendar-report/(?<path>.*), /$\{path}

        - id: crm-hook
          uri: http://crm-hook
          predicates:
            - Path=/api/crm3/*
        - id: crm-integration
          uri: http://crm-integration
          predicates:
            - Path=/api/crm/**
        - id: crm-api-doc
          uri: http://crm-integration
          predicates:
            - Path=/crm/**,/api/crm3/**
          filters:
            - RewritePath=/crm/(?<path>.*), /$\{path}

        - id: user-api
          uri: http://user-api
          predicates:
            - Path=/api/user/**,/api/auth/**
        - id: user-api-doc
          uri: http://user-api
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

        - id: video-conference-web-hook
          uri: http://vc-web-hook
          predicates:
            - Path=/api/video-conference/events/**

        - id: video-conference-api
          uri: http://vc-api
          predicates:
            - Path=/api/video-conference/**
        - id: video-conference-api-doc
          uri: http://vc-api
          predicates:
            - Path=/video-conference/**
          filters:
            - RewritePath=/video-conference/(?<path>.*), /$\{path}

        - id: customer-api
          uri: http://customer-api
          predicates:
            - Path=/api/customer/**
        - id: customer-api-doc
          uri: http://customer-api
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<path>.*), /$\{path}

        - id: customer-internal-api
          uri: http://customer-internal-api
          predicates:
            - Path=/api/internal/customer/**
        - id: customer-internal-api-doc
          uri: http://customer-internal-api
          predicates:
            - Path=/customer-internal/**
          filters:
            - RewritePath=/customer-internal/(?<path>.*), /$\{path}

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

        #
        #        - id: notification-api
        #          uri: lb://notification-api
        #          predicates:
        #            - Path=/api/notification/**
        #
        #        - id: notification-api-doc
        #          uri: lb://notification-api
        #          predicates:
        #            - Path=/notification/**
        #          filters:
        #            - RewritePath=/notification/(?<path>.*), /$\{path}
        #
        #

        - id: notification-api
          uri: http://notification-api
          predicates:
            - Path=/api/notification/**

        - id: notification-api-doc
          uri: http://notification-api
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<path>.*), /$\{path}