# SERVER -------------------------------------------------------------------------------------------
server:
  port: 8060

# SPRING -------------------------------------------------------------------------------------------
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: calendar-api
          uri: lb://calendar-api
          predicates:
            - Path=/api/calendar/**
        - id: calendar-api-doc
          uri: lb://calendar-api
          predicates:
            - Path=/calendar/**
          filters:
            - RewritePath=/calendar/(?<path>.*), /$\{path}

        - id: calendar-report-api
          uri: lb://calendar-report-api
          predicates:
          - Path=/api/calendar-report/**
        - id: calendar-report-api-doc
          uri: lb://calendar-report-api
          predicates:
          - Path=/calendar-report/**
          filters:
          - RewritePath=/calendar-report/(?<path>.*), /$\{path}

        - id: crm-integration
          uri: lb://crm-integration
          predicates:
          - Path=/api/crm/**,/api/crm3/**
        - id: crm-api-doc
          uri: lb://crm-integration
          predicates:
          - Path=/crm/**,/api/crm3/**
          filters:
          - RewritePath=/crm/(?<path>.*), /$\{path}

        - id: user-api
          uri: lb://user-api
          predicates:
            - Path=/api/user/**,/api/auth/**
        - id: user-api-doc
          uri: lb://user-api
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

        - id: video-conference-api
          uri: lb://video-conference-api
          predicates:
            - Path=/api/video-conference/**
        - id: video-conference-api-doc
          uri: lb://video-conference-api
          predicates:
            - Path=/video-conference/**
          filters:
            - RewritePath=/video-conference/(?<path>.*), /$\{path}

        - id: customer-api
          uri: lb://customer-api
          predicates:
            - Path=/api/customer/**
        - id: customer-api-doc
          uri: lb://customer-api
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<path>.*), /$\{path}

        - id: customer-internal-api
          uri: lb://customer-internal-api
          predicates:
            - Path=/api/internal/customer/**
        - id: customer-internal-api-doc
          uri: lb://customer-internal-api
          predicates:
            - Path=/customer-internal/**
          filters:
            - RewritePath=/customer-internal/(?<path>.*), /$\{path}

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

        - id: notification-api
          uri: lb://notification-api
          predicates:
            - Path=/api/notification/**

        - id: notification-api-doc
          uri: lb://notification-api
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<path>.*), /$\{path}
