# SPRING -------------------------------------------------------------------------------------------
spring:
  ## MONGODB ---------------------------------------------------------------------------------------
  # lab
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://tutorUserLab:e62c032fb984fbd81129019d0fd7b11d@172.16.7.210:27018/tutor_lab01

  ## MYSQL -----------------------------------------------------------------------------------------
  # lab
  datasource:
    url: jdbc:mysql://172.16.7.232:3306/tutor?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mpv6g1eAD8XB

application:
  common-google-auth:
    credential:
      google-drive:
        json-path: "D:/edupia/tutor-2022/core/core-google-drive/google-drive-config/credentials.json"
      firebase:
        json-path: "D:/edupia/tutor-2022/core/firebase-client/firebase-config/credentials.json"
  torus:
    base-url: "https://edupia-dev.toruslab.ai"
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc4NjUyNzEwNH0.1gSigefW6MIWugpAQmLzMGjCyFOyQ0U_PTM_QydrPgQ
    log-level: "HEADERS"
