# APPLICATION --------------------------------------------------------------------------------------

application:

  test-mode:
    enable: true
  ## ccm-integration --------------------------------------------------------------------------------------
  ccm-integration:
    base-url: "https://ccm-api-dev.educa.vn"
    cms-core-base-url: "https://api-cms-core-dev.edupia.com.vn"
    cms-core-token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJfdHV0b3IiLCJpYXQiOjE2ODg2MTc0NjUsImV4cCI6MTcyMDE1MzQ2NX0.W-dAJBntMw8bj0FsTGGuz2q-3AT9snJqmJNVcz8s6Dk"
    #    kafka-base-url: "222.252.28.124:19093"
    kafka-base-url: "kafka.educa.vn:19093,222.252.28.124:19093"
    kafka-password: "AyqYxp/UCQ7QcA=="
    kafka-topic-action-license: "user-action-license-2"
    kafka-username: "edupiatutor_dev"
    token: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJDQ00iLCJpYXQiOjE2NzU4Mzg0NDIsImV4cCI6MjU5MTE5ODQ0Mn0.LRM_4f3nKh2IgHB_zNIafZFvpxCWNVWhxEq5GMLfW9pNGolMqYYVtgMMWffwUWhT-oyyybcVSGqQ3KtcFT3U4Q"
  edupia:
    base-url: "https://service3-dev.edupia.com.vn"
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlkdGh1eWNoaSIsInVzZXJfaWQiOjY5NTg5MjQsImlhdCI6MTcwMTY1MzY0NSwiZXhwIjoxNzk2MzI2NDQ1fQ.ZMI97hrOARzYwcQ8n5Fxd-yO3oHds9yKJ0o5wDTaSXQ
    minGradeTH: 3
    domain: "https://learning-api.edupia.com.vn"
    url: "/tutor/filter-report-exam-months"
    api_token_header: "api-token"
    api_token: "xxx"
    khaothi-url: "https://khaothi-dev.edupia.com.vn"
  ## calendar --------------------------------------------------------------------------------------
  calendar:
    calendar_report:
      student-detail-info:
        lms_student_url: 'http://lms.edupiatutor.com.vn'
    arrange-class:
      regular:
        arrange-types-ignored: 'CHANGE_CLASS_IN_FUTURE'
        hour-will-create-class: 9
        product-type-codes-ignored: ''
        increase-level-day: '20240909'
    holidays: '{20250901,20250902}'
    homeroom-teacher-default: '6526'
    event:
      kafka_topic_task_prepare: "tutor_lab.tutor.task_prepare"
      kafka_topic_student_info: "tutor_lab.tutor.student_info"
      kafka_topic_task_weekly_exercise: "tutor_lab.tutor.task_weekly_exercise"
      kafka_topic_task_after_school_care: "tutor_lab.tutor.task_after_school_care"
      kafka_topic_class_demo: "tutor_lab.tutor.class_demo"
      kafka_topic_class_demo_student: "tutor_lab.tutor.class_demo_student"
      kafka_topic_class_regular_session: "tutor_lab.tutor.class_regular_session"
      kafka_topic_class_teacher_schedule: "tutor_lab.tutor.class_teacher_schedule"
      kafka_topic_crm_order: "tutor_lab.tutor.crm_order"
      kafka_topic_mdl_user_info_data: "tutor_lab.tutor.mdl_user_info_data"
      kafka_topic_mdl_role_assignments: "tutor_lab.tutor.mdl_role_assignments"
      kafka_topic_task_monitor_session: "tutor_lab.tutor.task_monitor_session"
      kafka_topic_class_regular_session_student: "tutor_lab.tutor.class_regular_session_student"
      kafka_topic_task_arrange_class: "tutor_lab.tutor.task_arrange_class"
      kafka_topic_class_regular_student: "tutor_lab.tutor.class_regular_student"
      kafka_topic_class_regular: "tutor_lab.tutor.class_regular"
      kafka_topic_task_support_technical: "tutor_lab.tutor.task_support_technical"
      kafka_topic_task_review_demo: "tutor_lab.tutor.task_review_demo"
      kafka_topic_teacher_classify_detail: "tutor_lab.tutor.teacher_classify_detail"
      kafka_topic_teacher_classify: "tutor_lab.tutor.teacher_classify"
      kafka_topic_mdl_user: "tutor_lab.tutor.mdl_user"
      kafka_topic_task_arrange_make_up_session: "tutor_lab.tutor.task_arrange_make_up_session"
      kafka_topic_reservation_form: "tutor_lab.tutor.reservation_form"
      kafka_topic_student_transfer: "tutor_lab.tutor.student_transfer"
      kafka_topic_student_arrange_class_result: "tutor_lab.tutor.student_arrange_class_result"
      kafka_topic_evaluate_session: "tutor_lab.tutor.evaluate_session"
      kafka_topic_teacher_level_teacher: "tutor_lab.tutor.teacher_level_teacher"
      kafka_topic_teacher_confirm_schedule_suggest: "tutor_lab.tutor.teacher_confirm_schedule_suggest"
      kafka_topic_task_teacher_schedule_urgent_cancel: "tutor_lab.tutor.task_teacher_schedule_urgent_cancel"
      kafka_topic_ccm_zalo_processor: "tutor_lab.tutor.ccm_zalo_processor"
      kafka_topic_task: "tutor_lab.tutor.task"
      kafka_topic_violation_level_teacher: "tutor_lab.tutor.violation_level_teacher"
      kafka_topic_task_arrange_class_detail: "tutor_lab.tutor.task_arrange_class_detail"
      kafka_topic_task_greeting_call: "tutor_lab.tutor.task_greeting_call"
      kafka_topic_task_take_care: "tutor_lab.tutor.task_take_care"
      kafka_topic_task_change_class_teacher: "tutor_lab.tutor.task_change_class_teacher"
      kafka_topic_student_program_conversion: "tutor_lab.tutor.student_program_conversion"
      kafka_topic_teacher_contract_terminated: "tutor_lab.tutor.teacher_contract_terminated"
      kafka_topic_task_change_demo_schedule: "tutor_lab.tutor.task_change_demo_schedule"
      kafka_topic_class_regular_schedule: "tutor_lab.tutor.class_regular_schedule"
      kafka_topic_report_tutor_quality: "tutor_lab.tutor.report_tutor_quality"
      kafka_topic_quality_control_session: "tutor_lab.tutor.quality_control_session"
      kafka_topic_teacher_info: "tutor_lab.tutor.teacher_info"
      kafka_topic_estimated_expired_date: "tutor_lab.tutor.estimated_expired_date"
      kafka_topic_task_monitor_backup: "tutor_lab.tutor.task_monitor_backup"
      kafka_topic_user_survey: "tutor_lab.tutor.user_survey"
      kafka_topic_user_survey_notification: "tutor_lab.tutor.user_survey_notification"
      kafka_topic_crm_bitrix_deal: "tutor_lab.tutor.crm_bitrix_deal"
      kafka_topic_class_training: "tutor_lab.tutor.class_training"
      kafka_topic_class_training_student: "tutor_lab.tutor.class_training_student"
      kafka_topic_class_training_session: "tutor_lab.tutor.class_training_session"
      kafka_topic_class_training_session_student: "tutor_lab.tutor.class_training_session_student"
      kafka_topic_task_parent_feedback: "tutor_lab.tutor.task_parent_feedback"
      kafka_topic_tm_group_teacher: "tutor_lab.tutor.tm_group_teacher"
      kafka_topic_center: "tutor_lab.tutor.center"
      kafka_topic_class_room: "tutor_lab.tutor.class_room"
      kafka_topic_user_center: "tutor_lab.tutor.user_center"
      kafka_topic_teacher_schedule_keeping: "tutor_lab.tutor.teacher_schedule_keeping"
      kafka_topic_mgmt_class_in_account: "tutor_lab.tutor.mgmt_class_in_account"
      kafka_topic_teacher_subject: "tutor_lab.tutor.teacher_subject"
      kafka_topic_quality_control_class_demo: "tutor_lab.tutor.quality_control_class_demo"
      kafka_topic_teacher_schedule_keeping_detail: "tutor_lab.tutor.teacher_schedule_keeping_detail"

    quarterly_exam:
      study_programs: 65800dc6-a15c-4d2b-8120-879545eeb26e,c9e640d4-6d3d-49fc-8fe5-bc59f0bca308,e3018785-cf19-404b-8341-04e7a31113a0,e3018785-cf19-404b-8341-04e7a3114567,e3018785-cf19-404b-8341-04e7a31145b0
      start_date: 20240615
      end_date: 20240630

  torus:
    base-url: "https://edupia-dev.toruslab.ai"
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc4NjUyNzEwNH0.1gSigefW6MIWugpAQmLzMGjCyFOyQ0U_PTM_QydrPgQ
    log-level: "BODY"


  user:
    event:
      kafka_topic_student_remain: "tutor_lab.tutor.student_remain"
      kafka_topic_parents_feedback: "tutor_lab.tutor.parents_feedback"