# SERVER -------------------------------------------------------------------------------------------
server:
  port: 8061

# EUREKA -------------------------------------------------------------------------------------------
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  config.activate.on-profile: k8s

eureka:
  instance:
    hostname: service-discovery
