server:
  port: 8088

spring:
  application:
    name: lms-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Projects/edupia/tutor-2022/cloud-service/config-server/src/main/resources/config
